# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'cca0385e-a761-4584-b04a-9ee2a355643b'
  imageRepository: 'front-end'
  containerRegistry: 'slackcpyacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile.prod'
  tag: 'latest'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)
        
- stage: Deploy
  displayName: Deploy to Azure App Service
  jobs: 
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Free Trial(21739d37-7de3-412c-91d0-105c69be8462)'
        appType: 'webAppContainer'
        WebAppName: 'SlackCpy'
        DockerNamespace: 'front-end'
        DockerRepository: 'slackcpyacr.azurecr.io/front-end'
        DockerImageTag: 'latest'
